from __future__ import annotations

from typing import Any


CONTRACTS_SCHEMA = "agentledger.contracts.v1"
CONTRACTS_DOC = "docs/json-contracts.md"

JSON_CONTRACTS: list[dict[str, Any]] = [
    {
        "command": "doctor --json",
        "schema_version": "agentledger.doctor.v1",
        "purpose": "Check local AgentLedger setup readiness.",
        "stable_fields": ["status", "required_ok", "optional", "checks"],
        "exit_codes": {"0": "ready", "2": "blocked"},
    },
    {
        "command": "open-latest --format json",
        "schema_version": "agentledger.open_latest.v1",
        "purpose": "Locate the latest local evidence without parsing text output.",
        "stable_fields": [
            "ok",
            "repo",
            "out",
            "latest_run",
            "paths",
            "missing_reports",
            "errors",
        ],
        "exit_codes": {"0": "latest run resolved", "2": "latest run or report files missing"},
    },
    {
        "command": "history --format json",
        "schema_version": "agentledger.history.v1",
        "purpose": "List recent runs from an AgentLedger output directory.",
        "stable_fields": ["out", "runs"],
        "exit_codes": {"0": "history listed", "2": "invalid output directory or options"},
    },
    {
        "command": "status --format json",
        "schema_version": "agentledger.status.v1",
        "purpose": "Summarize latest run policy, evidence paths, feedback counts, and next actions.",
        "stable_fields": [
            "ok",
            "status",
            "repo",
            "out",
            "latest_run",
            "paths",
            "missing_reports",
            "check",
            "feedback",
            "next_actions",
            "errors",
            "status_exit_code",
        ],
        "exit_codes": {
            "0": "latest run passed, or warned with warnings allowed",
            "1": "latest run has warnings",
            "2": "latest run is blocked, missing, or unreadable",
        },
    },
    {
        "command": "alpha-guide --format json",
        "schema_version": "agentledger.alpha_guide.v1",
        "purpose": "Show the first-run alpha review loop without creating evidence.",
        "stable_fields": [
            "ok",
            "repo",
            "out",
            "commands",
            "evidence",
            "send_back",
            "keep_private",
            "known_limitations",
            "errors",
        ],
        "exit_codes": {"0": "guide printed", "2": "config invalid"},
    },
    {
        "command": "alpha --format json",
        "schema_version": "agentledger.alpha_summary.v1",
        "purpose": "Run the core alpha pass and write a machine-readable summary.",
        "stable_fields": [
            "ok",
            "summary_file",
            "started_at",
            "ended_at",
            "repo",
            "out",
            "latest_run",
            "bundle",
            "agentledger_version",
            "python_version",
            "git_version",
            "doctor",
            "status",
            "status_summary",
            "status_exit_code",
            "report_paths",
            "feedback",
            "next_actions",
            "errors",
        ],
        "exit_codes": {"0": "alpha pass valid", "2": "alpha pass failed, blocked, or summary invalid"},
    },
    {
        "command": "alpha-summary --format json",
        "schema_version": "agentledger.alpha_summary.v1",
        "purpose": "Inspect and validate the one-command alpha pass summary.",
        "stable_fields": [
            "ok",
            "summary_file",
            "started_at",
            "ended_at",
            "repo",
            "out",
            "latest_run",
            "bundle",
            "agentledger_version",
            "python_version",
            "git_version",
            "doctor",
            "status",
            "status_summary",
            "status_exit_code",
            "report_paths",
            "feedback",
            "next_actions",
            "errors",
        ],
        "exit_codes": {"0": "summary valid", "2": "summary missing, invalid, or recorded errors"},
    },
    {
        "command": "alpha-handoff --format json --output-dir <dir>",
        "schema_version": "agentledger.alpha_handoff.v1",
        "purpose": "Write a reviewed alpha handoff packet without copying raw evidence.",
        "stable_fields": [
            "ok",
            "status",
            "summary",
            "generated_at",
            "agentledger_version",
            "repo",
            "out",
            "latest_run",
            "output_dir",
            "files",
            "share_safe",
            "redactions",
            "review",
            "status_payload",
            "feedback_summary",
            "alpha_summary",
            "handling",
            "next_actions",
            "errors",
        ],
        "exit_codes": {
            "0": "handoff written for pass, or warn without strict mode",
            "2": "handoff missing evidence, blocked, failed, or warned in strict mode",
        },
    },
    {
        "command": "pack-alpha --format json --output-dir <dir>",
        "schema_version": "agentledger.pack_alpha.v1",
        "purpose": "Write and validate a share-safe alpha handoff packet.",
        "stable_fields": [
            "ok",
            "status",
            "summary",
            "generated_at",
            "agentledger_version",
            "repo",
            "output_dir",
            "files",
            "raw_evidence_copied",
            "handoff_exit_code",
            "handoff",
            "validation",
            "next_actions",
            "errors",
        ],
        "exit_codes": {
            "0": "share-safe packet written and validation passed",
            "2": "handoff failed or generated packet validation failed",
        },
    },
    {
        "command": "feedback --format json --note <text>",
        "schema_version": "agentledger.feedback.v1",
        "purpose": "Record or list local alpha feedback attached to a run.",
        "stable_fields": [
            "ok",
            "action",
            "run_dir",
            "feedback_file",
            "entry",
            "entries",
            "errors",
        ],
        "exit_codes": {"0": "feedback recorded or listed", "2": "invalid input or missing run"},
    },
    {
        "command": "feedback-summary --format json",
        "schema_version": "agentledger.feedback_summary.v1",
        "purpose": "Summarize local alpha feedback across run folders.",
        "stable_fields": [
            "ok",
            "out",
            "filters",
            "total_entries",
            "returned_entries",
            "run_count",
            "runs_with_feedback",
            "categories",
            "severities",
            "runs",
            "entries",
            "errors",
        ],
        "exit_codes": {"0": "feedback summarized", "2": "invalid input, output missing, or feedback unreadable"},
    },
    {
        "command": "feedback-export --format json --output <path>",
        "schema_version": "agentledger.feedback_export_result.v1",
        "purpose": "Write a reviewed feedback export that omits local evidence paths.",
        "stable_fields": [
            "ok",
            "out",
            "output",
            "output_format",
            "export_schema_version",
            "filters",
            "total_entries",
            "returned_entries",
            "run_count",
            "runs_with_feedback",
            "errors",
        ],
        "exit_codes": {"0": "feedback export written", "2": "invalid input, output missing, or feedback unreadable"},
    },
    {
        "command": "inspect-report --format json <run-dir>",
        "schema_version": "agentledger.inspect_report.v1",
        "purpose": "Summarize one run report.",
        "stable_fields": [
            "run_dir",
            "command",
            "exit_code",
            "test_framework",
            "changed_files",
            "artifacts",
            "tokometer",
            "privacy_mode",
        ],
        "exit_codes": {"0": "report inspected", "2": "report missing or unreadable"},
    },
    {
        "command": "check --format json <run-dir>",
        "schema_version": "agentledger.check.v1",
        "purpose": "Evaluate a run report against review policy.",
        "stable_fields": [
            "status",
            "ok",
            "run_dir",
            "report",
            "summary",
            "rule_counts",
            "warning_rules",
            "blocking_rules",
            "rules",
            "policy",
        ],
        "exit_codes": {
            "0": "pass, or warn with warnings allowed",
            "1": "warn",
            "2": "block or invalid input",
        },
    },
    {
        "command": "review --format json [--output <path>]",
        "schema_version": "agentledger.review.v1",
        "purpose": "Combine policy status with direct evidence paths, recent-run context, and previous-run comparison.",
        "stable_fields": [
            "status",
            "ok",
            "summary",
            "run_dir",
            "command_exit_code",
            "paths",
            "history",
            "comparison",
            "check",
            "output",
            "review_exit_code",
        ],
        "exit_codes": {
            "0": "pass, or warn with warnings allowed",
            "1": "warn",
            "2": "block or invalid input",
        },
    },
    {
        "command": "signing-key --format json --key-file <key>",
        "schema_version": "agentledger.signing_key.v1",
        "purpose": "Check shared signing-key file safety without printing key material.",
        "stable_fields": [
            "ok",
            "key_file",
            "repo",
            "git_root",
            "exists",
            "file",
            "size_bytes",
            "empty",
            "inside_repo",
            "ignored_by_git",
            "tracked_by_git",
            "warnings",
            "errors",
            "next_actions",
        ],
        "exit_codes": {"0": "key file exists and repo safety checks pass", "2": "key missing, empty, tracked, unignored, or unsafe"},
    },
    {
        "command": "sign-bundle --format json <bundle.zip> --key-file <key>",
        "schema_version": "agentledger.sign_bundle.v1",
        "purpose": "Add or replace a shared-key HMAC signature on a portable evidence bundle.",
        "stable_fields": [
            "ok",
            "bundle",
            "signed_bundle",
            "signature",
            "errors",
        ],
        "exit_codes": {"0": "bundle signed", "2": "bundle missing, invalid, key missing, or signing failed"},
    },
    {
        "command": "inspect-bundle --format json <bundle.zip>",
        "schema_version": "agentledger.inspect_bundle.v1",
        "purpose": "Summarize a portable evidence bundle before full verification.",
        "stable_fields": [
            "ok",
            "bundle",
            "readable",
            "manifest",
            "signature",
            "reports",
            "review",
            "errors",
            "next_actions",
        ],
        "exit_codes": {"0": "bundle inspected", "2": "bundle missing, unreadable, or report unavailable"},
    },
    {
        "command": "verify-bundle --format json <bundle.zip>",
        "schema_version": "agentledger.verify_bundle.v1",
        "purpose": "Validate a portable evidence bundle.",
        "stable_fields": [
            "ok",
            "bundle",
            "run_id",
            "manifest",
            "signature",
            "reports",
            "command",
            "changed_files",
            "artifacts",
            "errors",
        ],
        "exit_codes": {"0": "bundle valid", "2": "bundle missing, invalid, or verification failed"},
    },
    {
        "command": "compare --format json <old-run> <new-run>",
        "schema_version": "agentledger.compare.v1",
        "purpose": "Compare two captured runs.",
        "stable_fields": [
            "changed_files",
            "exit_code",
            "artifacts",
            "command",
            "tokometer",
            "test_framework",
            "privacy_mode",
        ],
        "exit_codes": {"0": "reports compared", "2": "one or both reports missing or unreadable"},
    },
    {
        "command": "contracts --format json",
        "schema_version": CONTRACTS_SCHEMA,
        "purpose": "List AgentLedger JSON command contracts.",
        "stable_fields": [
            "schema_version",
            "agentledger_version",
            "docs",
            "compatibility",
            "contracts",
        ],
        "exit_codes": {"0": "contracts listed"},
    },
]


def build_contracts_payload(agentledger_version: str) -> dict[str, Any]:
    return {
        "schema_version": CONTRACTS_SCHEMA,
        "agentledger_version": agentledger_version,
        "docs": CONTRACTS_DOC,
        "compatibility": {
            "stability": "alpha",
            "unknown_fields": "ignore",
            "breaking_changes": "schema_version changes when payload meaning or shape breaks compatibility",
        },
        "contracts": JSON_CONTRACTS,
    }


def format_contracts_text(agentledger_version: str) -> str:
    lines = [
        f"AgentLedger JSON contracts ({agentledger_version})",
        f"Schema: {CONTRACTS_SCHEMA}",
        f"Docs: {CONTRACTS_DOC}",
        "Commands:",
    ]
    for contract in JSON_CONTRACTS:
        lines.append(f"- {contract['command']}: {contract['schema_version']}")
    return "\n".join(lines)
